# @name staffLogin
POST {{baseUrl}}/api/{{apiVersion}}/staff/login/
Content-Type: application/json

{
  "phone": "{{staffPhone}}",
  "password": "{{staffPassword}}"
}

###
POST {{baseUrl}}/api/{{apiVersion}}/token/refresh/
Content-Type: application/json

{
  "refresh": "{{staffLogin.response.body.data.refresh}}"
}
