# Generated by Django 5.2.9 on 2025-12-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="worker",
            name="company_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="worker",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worker",
            name="emirates_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="worker",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
