# Generated by Django 5.2.9 on 2025-12-24 01:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_worker_company_name_worker_company_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="full_name",
        ),
    ]
