# Generated by Django 6.0 on 2025-12-26 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_staff_full_name_remove_worker_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staffs",
                to="accounts.company",
            ),
        ),
    ]
