# Generated by Django 5.2.9 on 2025-12-24 02:00

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0004_remove_staff_full_name_remove_worker_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attendance_date", models.DateField()),
                (
                    "shift_type",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("sick", "Sick"),
                            ("site_out", "Site Out"),
                            ("no_work", "No Work"),
                            ("safety", "Safety"),
                            ("training", "Training"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date_time", models.DateTimeField(blank=True, null=True)),
                ("end_date_time", models.DateTimeField(blank=True, null=True)),
                ("worker_start_date_time", models.DateTimeField(blank=True, null=True)),
                ("worker_end_date_time", models.DateTimeField(blank=True, null=True)),
                ("staff_start_date_time", models.DateTimeField(blank=True, null=True)),
                ("staff_end_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_shifts",
                        to="accounts.staff",
                    ),
                ),
                (
                    "recorded_by_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_shifts",
                        to="accounts.worker",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-attendance_date",
                    "recorded_by_worker",
                    "recorded_by_staff",
                ],
            },
        ),
        migrations.CreateModel(
            name="ShiftAudit",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attendance_date", models.DateField()),
                (
                    "shift_type",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("sick", "Sick"),
                            ("site_out", "Site Out"),
                            ("no_work", "No Work"),
                            ("safety", "Safety"),
                            ("training", "Training"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date_time", models.DateTimeField(blank=True, null=True)),
                ("end_date_time", models.DateTimeField(blank=True, null=True)),
                ("worker_start_date_time", models.DateTimeField(blank=True, null=True)),
                ("worker_end_date_time", models.DateTimeField(blank=True, null=True)),
                ("staff_start_date_time", models.DateTimeField(blank=True, null=True)),
                ("staff_end_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_by_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_audits",
                        to="accounts.staff",
                    ),
                ),
                (
                    "recorded_by_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_audits",
                        to="accounts.worker",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="shifts.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorded_by_worker__isnull", False)),
                fields=("recorded_by_worker", "attendance_date"),
                name="uniq_attendance_worker_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorded_by_staff__isnull", False)),
                fields=("recorded_by_staff", "attendance_date"),
                name="uniq_attendance_staff_date",
            ),
        ),
    ]
