# Generated by Django 6.0 on 2025-12-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shift_latitude_shift_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='longitude',
        ),
        migrations.AddField(
            model_name='shift',
            name='worker_end_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='worker_start_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
