# Generated by Django 6.0 on 2025-12-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_remove_shift_latitude_remove_shift_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftaudit',
            name='worker_end_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftaudit',
            name='worker_start_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
