# Generated by Django 6.0 on 2025-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_shiftaudit_worker_end_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('no_bus', 'No Bus'), ('missed_bus', 'Missed Bus'), ('site_out', 'Site Out'), ('no_work', 'No Work'), ('safety', 'Safety'), ('training', 'Training')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shiftaudit',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('sick', 'Sick'), ('no_bus', 'No Bus'), ('missed_bus', 'Missed Bus'), ('site_out', 'Site Out'), ('no_work', 'No Work'), ('safety', 'Safety'), ('training', 'Training')], max_length=20, null=True),
        ),
    ]
